import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {BacktestsDashboard} from "@/features/backtests/components/backtests-dashboard";
import {percent} from "@/features/backtests/format";
vi.mock("next/link",()=>({default:({children,href,...p}:React.AnchorHTMLAttributes<HTMLAnchorElement>)=><a href={String(href)} {...p}>{children}</a>}));
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
const run=(id:string,status="completed")=>({id,strategy_name:"watchlist_entry",strategy_version:"1",parameters:{position_size:"500000.00000000"},start_date:"2026-01-01",end_date:"2026-06-01",data_as_of:null,status,created_at:`2026-07-0${id}T00:00:00Z`,started_at:null,completed_at:null,result:status==="completed"?{total_signals:3,entered_trades:2,skipped_signals:1,net_profit:"10.00000000",total_return:"0.00000200",win_rate:"0.50000000",average_holding_days:"2.00000000"}:null,failure_code:status==="failed"?"DATA_ERROR":null,failure_message:status==="failed"?"No data":null});
describe("backtests dashboard",()=>{beforeEach(()=>{cleanup();vi.restoreAllMocks()});it("renders loading then empty state and navigation",async()=>{vi.spyOn(globalThis,"fetch").mockReturnValue(response([]));render(<BacktestsDashboard/>);expect(screen.getByRole("status")).toHaveTextContent("불러오는 중");expect(await screen.findByText("저장된 백테스트 실행이 없습니다.")).toBeVisible();expect(screen.getByRole("link",{name:"백테스트"})).toHaveAttribute("href","/backtests")});it("validates dates without submitting",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockReturnValue(response([]));render(<BacktestsDashboard/>);await screen.findByText("저장된 백테스트 실행이 없습니다.");fireEvent.change(screen.getByLabelText("시작일"),{target:{value:"2026-12-31"}});fireEvent.change(screen.getByLabelText("종료일"),{target:{value:"2026-01-01"}});fireEvent.click(screen.getByRole("button",{name:/watchlist_entry/}));expect(await screen.findByRole("alert")).toHaveTextContent("시작일");expect(fetch).toHaveBeenCalledTimes(1)});it("retries an API failure",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockReturnValueOnce(response({},500)).mockReturnValue(response([]));render(<BacktestsDashboard/>);fireEvent.click(await screen.findByRole("button",{name:"다시 시도"}));expect(await screen.findByText("저장된 백테스트 실행이 없습니다.")).toBeVisible();expect(fetch).toHaveBeenCalledTimes(2)});it("selects a failed run and renders failure detail",async()=>{const failed=run("1","failed");vi.spyOn(globalThis,"fetch").mockImplementation(url=>String(url).includes("/trades?")?response([]):response(String(url).endsWith("/backtests")?[failed]:failed));render(<BacktestsDashboard/>);fireEvent.click(await screen.findByRole("button",{name:/2026/}));expect(await screen.findByText("No data")).toBeVisible();expect(screen.getAllByText("DATA_ERROR").length).toBeGreaterThan(0)});it("compares two completed persisted runs and blocks non-completed selection",async()=>{const runs=[run("2"),run("1"),run("3","failed")];vi.spyOn(globalThis,"fetch").mockReturnValue(response(runs));render(<BacktestsDashboard/>);const boxes=await screen.findAllByRole("checkbox");expect(screen.getByLabelText("3 비교 선택")).toBeDisabled();fireEvent.click(screen.getByLabelText("2 비교 선택"));fireEvent.click(screen.getByLabelText("1 비교 선택"));expect(await screen.findByRole("heading",{name:"실행 1"})).toBeVisible();expect(screen.getAllByText(/더 높음|같음|더 낮음|비교 불가/).length).toBeGreaterThan(0)})});
describe("precise formatting",()=>{it("scales decimal percentages without floating point conversion",()=>expect(percent("0.1234567890123456789")).toBe("12.34567890123456789%"))});
