import { cleanup, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { BacktestPortfolio } from "@/features/backtests/components/backtest-portfolio";
import { clearBacktestPortfolioCache, loadBacktestPortfolio } from "@/features/backtests/portfolio-cache";

const result = {run_id:"p1",execution_mode:"portfolio",initial_capital:"1000.00000000",final_equity:"1001.00000000",final_cash:"1001.00000000",net_profit:"1.00000000",total_return:"0.00100000",max_drawdown:"2.00000000",max_drawdown_pct:"0.00200000",maximum_open_positions_used:1,average_capital_utilization:"0.10000000",snapshots:[{trading_date:"2026-01-02",cash:"900.00000000",market_value:"100.00000000",realized_pnl:"0.00000000",unrealized_pnl:"0.00000000",total_equity:"1000.00000000",cumulative_return:"0.00000000",running_peak_equity:"1000.00000000",drawdown:"0.00000000",drawdown_pct:"0.00000000",open_position_count:1}]};
const response = (body: unknown, status=200) => Promise.resolve(new Response(JSON.stringify(body), {status,headers:{"Content-Type":"application/json"}}));
beforeEach(()=>{clearBacktestPortfolioCache();cleanup();vi.restoreAllMocks()});afterEach(cleanup);
describe("portfolio analysis",()=>{
 it("deduplicates in-flight requests, caches results, and renders exact accessible data",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockImplementation(()=>response(result));const [a,b]=await Promise.all([loadBacktestPortfolio("p1"),loadBacktestPortfolio("p1")]);expect(a).toBe(b);expect(fetch).toHaveBeenCalledTimes(1);render(<BacktestPortfolio runId="p1"/>);expect(await screen.findByText("900.00000000")).toBeInTheDocument();expect(screen.getByRole("img",{name:/일별 포트폴리오 자산.*1000.00000000/})).toBeInTheDocument();expect(screen.getByRole("img",{name:/포트폴리오 낙폭.*drawdown_pct 0.00000000/})).toBeInTheDocument();expect(fetch).toHaveBeenCalledTimes(1)});
 it("shows a safe unavailable state rather than coercing non-finite coordinates",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(()=>response({...result,snapshots:[{...result.snapshots[0],total_equity:"1e10000"}]}));render(<BacktestPortfolio runId="huge"/>);expect(await screen.findByText(/안전하게 표시할 수 없습니다/)).toBeInTheDocument();expect(screen.getByText("1e10000")).toBeInTheDocument()});
 it("ignores a stale response after the selected run changes",async()=>{let resolveFirst:(value:Response)=>void=()=>undefined;vi.spyOn(globalThis,"fetch").mockImplementation((url)=>String(url).includes("old")?new Promise(resolve=>{resolveFirst=resolve}):response({...result,run_id:"new"}));const view=render(<BacktestPortfolio runId="old"/>);view.rerender(<BacktestPortfolio runId="new"/>);await screen.findAllByText("1001 원");resolveFirst(new Response(JSON.stringify({...result,final_equity:"999.00000000"}),{headers:{"Content-Type":"application/json"}}));await waitFor(()=>expect(screen.queryByText("999 원")).not.toBeInTheDocument())});
});
