import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { clearBacktestAnalysisCache } from "@/features/backtests/analysis-cache";
import { getBacktestAnalysis } from "@/features/backtests/api";
import { BacktestAnalysis } from "@/features/backtests/components/backtest-analysis";
import { BacktestComparison } from "@/features/backtests/components/backtest-comparison";
import type { BacktestAnalysis as Analysis, BacktestRun } from "@/features/backtests/types";
const json=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
function analysis(id="analysis-1"):Analysis{return {run_id:id,trade_count:2,summary:{winning_trades:1,losing_trades:1,breakeven_trades:0,win_rate:"0.50000000",gross_profit:"12345678901234567890.12345678",gross_loss:"-2.00000000",net_profit:"12345678901234567888.12345678",average_trade_pnl:"-1.25000000",average_win:"12345678901234567890.12345678",average_loss:"-2.00000000",largest_win:"12345678901234567890.12345678",largest_loss:"-2.00000000",profit_factor:"6172839450617283945.06172839",average_holding_days:"2.50000000",max_consecutive_wins:1,max_consecutive_losses:1,max_realized_pnl_drawdown:"2.00000000"},cumulative_realized_pnl:[{sequence:1,trade_id:"t1",exit_date:"2026-01-01",symbol:"AAA",exit_reason:"take_profit",net_pnl:"12345678901234567890.12345678",cumulative_net_pnl:"12345678901234567890.12345678",running_peak:"12345678901234567890.12345678",realized_drawdown:"0.00000000",realized_drawdown_pct:"0.00000000"}],by_symbol:[{symbol:"AAA",trade_count:2,winning_trades:1,losing_trades:1,breakeven_trades:0,win_rate:"0.5",gross_profit:"3",gross_loss:"-2",net_profit:"1",average_trade_pnl:"0.5",average_holding_days:"2",largest_win:"3",largest_loss:"-2"}],by_exit_reason:[{exit_reason:"take_profit",trade_count:2,trade_share:"1",winning_trades:1,losing_trades:1,breakeven_trades:0,win_rate:"0.5",net_profit:"1",average_trade_pnl:"0.5",average_holding_days:"2"}],by_month:[{month:"2026-01",trade_count:2,winning_trades:1,losing_trades:1,breakeven_trades:0,win_rate:"0.5",gross_profit:"3",gross_loss:"-2",net_profit:"1",average_trade_pnl:"0.5",average_holding_days:"2"}]};}
function run(id:string):BacktestRun{return{id,strategy_name:"watchlist_entry",strategy_version:"1",parameters:{},start_date:"2026-01-01",end_date:"2026-02-01",data_as_of:null,status:"completed",created_at:"2026-01-01T00:00:00Z",started_at:null,completed_at:null,result:{},failure_code:null,failure_message:null}}
beforeEach(()=>{cleanup();clearBacktestAnalysisCache();vi.restoreAllMocks()});afterEach(cleanup);
describe("realized analysis",()=>{
 it("deduplicates, caches, renders every summary field, charts, limitations and ordered tables",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockReturnValue(json(analysis()));const a=render(<BacktestAnalysis runId="analysis-1"/>);a.rerender(<><BacktestAnalysis runId="analysis-1"/><BacktestAnalysis runId="analysis-1"/></>);expect(screen.getAllByText("분석을 불러오는 중입니다.").length).toBeGreaterThan(0);expect(await screen.findAllByText("12345678901234567890.12345678 원")).not.toHaveLength(0);expect(fetch).toHaveBeenCalledTimes(1);for(const title of ["실현 거래 기준 누적 순손익","실현 손익 기준 낙폭","월별 실현 순손익"])expect(screen.getAllByRole("img",{name:title})[0]).toHaveAccessibleName(title);expect(screen.getAllByText(/미실현 손익과 포트폴리오 현금 제약/)[0]).toBeVisible();expect(document.body.textContent).not.toContain("equity curve");expect(document.body.textContent).not.toContain("portfolio drawdown");for(const title of ["종목별 성과","청산 사유별 성과","월별 성과"]){const section=screen.getAllByRole("heading",{name:title})[0].closest("section")!;expect(section.querySelector(".table-scroll")).not.toBeNull()}expect(screen.getAllByText("-2 원").length).toBeGreaterThan(0);a.unmount();render(<BacktestAnalysis runId="analysis-1"/>);await screen.findByText("실현 거래 분석");expect(fetch).toHaveBeenCalledTimes(1)});
 it("renders zero series, table empty states, and null placeholders",async()=>{const empty=analysis("empty-analysis");empty.trade_count=0;empty.summary={...empty.summary,win_rate:null,average_trade_pnl:null,average_win:null,average_loss:null,largest_win:null,largest_loss:null,profit_factor:null,average_holding_days:null};empty.cumulative_realized_pnl=[];empty.by_symbol=[];empty.by_exit_reason=[];empty.by_month=[];vi.spyOn(globalThis,"fetch").mockReturnValue(json(empty));render(<BacktestAnalysis runId="empty-analysis"/>);expect((await screen.findAllByText("표시할 데이터가 없습니다.")).length).toBeGreaterThanOrEqual(6);expect(screen.getAllByText("—").length).toBeGreaterThanOrEqual(8)});
 it("shows API detail through typed client and retries component failures",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockReturnValueOnce(json({detail:"Backtest run not found"},404)).mockReturnValueOnce(json({detail:"failure"},500)).mockReturnValueOnce(json(analysis("retry-analysis")));await expect(getBacktestAnalysis("missing")).rejects.toMatchObject({status:404,message:"Backtest run not found"});render(<BacktestAnalysis runId="retry-analysis"/>);fireEvent.click(await screen.findByRole("button",{name:"다시 시도"}));expect((await screen.findAllByText("실현 거래 기준 누적 순손익"))[0]).toBeVisible();expect(fetch).toHaveBeenCalledTimes(3)});
 it("parses stable 409 details",async()=>{vi.spyOn(globalThis,"fetch").mockReturnValue(json({detail:"Backtest analysis is available only for completed runs"},409));await expect(getBacktestAnalysis("pending")).rejects.toMatchObject({status:409,message:"Backtest analysis is available only for completed runs"})});
});
describe("analysis comparison",()=>{it("loads both independently, survives one failure, and uses neutral wording",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(url=>String(url).endsWith("/a/analysis")?json(analysis("a")):json({detail:"failure"},500));render(<BacktestComparison runs={[run("a"),run("b")]}/>);expect(await screen.findByText("12345678901234567888.12345678 원")).toBeVisible();expect(await screen.findAllByRole("alert")).toHaveLength(1);expect(screen.getByText(/높고 낮음은 우열을 뜻하지 않습니다/)).toBeVisible();expect(screen.getByText(/통계적 유의성을 주장하지 않으며/)).toBeVisible()});});
