import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { compareDecimalStrings, formatPercent, ScreenerDashboard } from "@/features/screener/screener-dashboard";

const definitions={screener_name:"multi_setup_swing",version:"1",setup_keys:["box_breakout"],setup_labels:{box_breakout:"박스권 돌파"}};
const execution={trading_date:"2026-07-29",status:"succeeded",started_at:"start",finished_at:"finish",candidate_count:1,persisted_count:1};
const candidate={rank:1,symbol:"005930",total_score:"91.00000000000000000001",primary_setup:"box_breakout",matched_setups:["box_breakout"],average_trading_value_20:"900719925474099312345.01",atr_pct:"0.00125",volume_ratio:"1.5",warnings:[]};
const reply=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}}));
const result=(items=[candidate])=>({execution_id:"execution-1",trading_date:"2026-07-28",screened_count:807,setup_passed_count:1,score_qualified_count:items.length,score_threshold:"80.00",result_count:items.length,items});
function standardFetch(runStatus=200){return vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest"))return reply(execution);if(url.endsWith("/admin/watchlist/run")&&init?.method==="POST")return reply(execution,runStatus);return reply(result());});}

describe("ScreenerDashboard",()=>{afterEach(cleanup);beforeEach(()=>{vi.restoreAllMocks();history.replaceState(null,"","/screener");});
 it("loads definitions, history, execution and exact candidate presentation",async()=>{standardFetch();render(<ScreenerDashboard/>);expect(await screen.findByText("multi_setup_swing v1")).toBeVisible();expect(screen.getByText(/최근 실행일: 2026-07-29/)).toBeVisible();expect(await screen.findByText("005930")).toBeVisible();expect(screen.getByText(/ATR: 0.125%/)).toBeVisible();expect(screen.getByText(/돌파 거래량 배수: 1.5/)).toBeVisible();});
 it("preserves leading-zero and unrelated URL state",async()=>{history.replaceState(null,"","/screener?q=005930&foreign=keep");standardFetch();render(<ScreenerDashboard/>);expect(await screen.findByDisplayValue("005930")).toBeVisible();expect(location.search).toContain("foreign=keep");expect(location.search).toContain("q=005930");});
 it("uses HTTP status for conflict and a safe generic run error",async()=>{standardFetch(409);render(<ScreenerDashboard/>);const button=await screen.findByRole("button",{name:"오늘 스크리닝"});fireEvent.click(button);expect(await screen.findByText("이미 스크리닝이 실행 중입니다.")).toBeVisible();vi.restoreAllMocks();standardFetch(500);fireEvent.click(button);expect(await screen.findByText("스크리닝 실행에 실패했습니다.")).toBeVisible();});
 it("treats missing execution history as a usable empty state",async()=>{vi.spyOn(globalThis,"fetch").mockImplementation(input=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest"))return reply({},404);return reply(result());});render(<ScreenerDashboard/>);expect(await screen.findByText("실행 이력 없음")).toBeVisible();expect(screen.getByRole("button",{name:"오늘 스크리닝"})).toBeEnabled();expect(await screen.findByText("005930")).toBeVisible();});
 it("explains a valid empty result with the searched count and score threshold",async()=>{const empty={...result([]),setup_passed_count:12,score_qualified_count:0};vi.spyOn(globalThis,"fetch").mockImplementation(input=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest"))return reply({...execution,screened_count:807,qualified_count:0,score_threshold:"80.00",persisted_count:0});return reply(empty);});render(<ScreenerDashboard/>);expect(await screen.findByRole("heading",{name:"오늘 기준을 충족한 종목이 없습니다"})).toBeVisible();expect(screen.getByText(/총/).textContent).toContain("807개");expect(screen.getByText(/총/).textContent).toContain("80점 이상");expect(screen.getByText(/억지로 추천하지 않은 정상 결과/)).toBeVisible();});
 it("retries the failed selected-date request",async()=>{let dated=0;vi.spyOn(globalThis,"fetch").mockImplementation(input=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest"))return reply(execution);if(url.endsWith("/screener/results/2026-07-28"))return ++dated===1?reply({},500):reply(result());return reply([]);});render(<ScreenerDashboard/>);const retry=await screen.findByRole("button",{name:"다시 시도"});fireEvent.click(retry);expect(await screen.findByText("005930")).toBeVisible();expect(dated).toBe(2);});
 it("refetches candidates after a successful same-date run",async()=>{const replacement={...candidate,symbol:"000660"};let dated=0;vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest"))return reply(execution);if(url.endsWith("/admin/watchlist/run")&&init?.method==="POST")return reply({...execution,trading_date:"2026-07-28"});if(url.endsWith("/screener/results/2026-07-28"))return reply(result([dated++===0?candidate:replacement]));return reply([]);});render(<ScreenerDashboard/>);expect(await screen.findByText("005930")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"오늘 스크리닝"}));expect(await screen.findByText("000660")).toBeVisible();expect(screen.queryByText("005930")).not.toBeInTheDocument();expect(dated).toBe(2);});
 it("disables duplicate run clicks while pending",async()=>{let resolveRun:(value:Response)=>void=()=>{};standardFetch();vi.mocked(fetch).mockImplementation((input)=>String(input).endsWith("/admin/watchlist/run")?new Promise(resolve=>{resolveRun=resolve}):String(input).endsWith("/screener/definitions")?reply(definitions):String(input).endsWith("/watchlist/history")?reply(["2026-07-28"]):String(input).endsWith("/admin/watchlist/executions/latest")?reply(execution):reply(result()));render(<ScreenerDashboard/>);const button=await screen.findByRole("button",{name:"오늘 스크리닝"});fireEvent.click(button);fireEvent.click(button);expect(button).toBeDisabled();resolveRun(new Response(JSON.stringify(execution),{status:200}));await waitFor(()=>expect(button).not.toBeDisabled());});
 it("confirms and sends an explicit selected-date reanalysis",async()=>{const confirm=vi.spyOn(window,"confirm").mockReturnValue(true);const fetch=standardFetch();render(<ScreenerDashboard/>);const button=await screen.findByRole("button",{name:"선택 날짜 다시 분석"});expect(button).toBeEnabled();fireEvent.click(button);await waitFor(()=>expect(fetch).toHaveBeenCalledWith(expect.stringContaining("/admin/watchlist/run"),expect.objectContaining({method:"POST",body:JSON.stringify({trading_date:"2026-07-28",force_reanalysis:true})})));expect(confirm).toHaveBeenCalledWith("저장된 시장 데이터로 2026-07-28 결과를 다시 계산합니다.");});
 it("does not request reanalysis when confirmation is cancelled",async()=>{vi.spyOn(window,"confirm").mockReturnValue(false);const fetch=standardFetch();render(<ScreenerDashboard/>);fireEvent.click(await screen.findByRole("button",{name:"선택 날짜 다시 분석"}));expect(fetch.mock.calls.some(([,init])=>init?.method==="POST")).toBe(false);});
 it("reloads same-date candidates after successful reanalysis",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const replacement={...candidate,symbol:"000660"};let dated=0;vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest"))return reply(execution);if(url.endsWith("/admin/watchlist/run")&&init?.method==="POST")return reply({...execution,trading_date:"2026-07-28",trigger_type:"manual_reanalysis"});if(url.endsWith("/screener/results/2026-07-28"))return reply(result([dated++===0?candidate:replacement]));return reply([]);});render(<ScreenerDashboard/>);expect(await screen.findByText("005930")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"선택 날짜 다시 분석"}));expect(await screen.findByText("000660")).toBeVisible();expect(dated).toBe(2);});
 it("preserves candidates and shows a reanalysis-specific conflict",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);standardFetch(409);render(<ScreenerDashboard/>);expect(await screen.findByText("005930")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"선택 날짜 다시 분석"}));expect(await screen.findByText("다른 분석이 실행 중이거나 이전 성공 이력이 없습니다.")).toBeVisible();expect(screen.getByText("005930")).toBeVisible();});
it("does not replace successful execution with an already-completed skip",async()=>{let latestCalls=0;vi.spyOn(globalThis,"fetch").mockImplementation((input,init)=>{const url=String(input);if(url.endsWith("/screener/definitions"))return reply(definitions);if(url.endsWith("/watchlist/history"))return reply(["2026-07-28"]);if(url.endsWith("/admin/watchlist/executions/latest")){latestCalls+=1;return reply(execution);}if(url.endsWith("/admin/watchlist/run")&&init?.method==="POST")return reply({...execution,status:"skipped",skipped_reason:"already_completed",candidate_count:null,persisted_count:null});return reply(result());});render(<ScreenerDashboard/>);await screen.findByText(/상태: succeeded/);fireEvent.click(screen.getByRole("button",{name:"오늘 스크리닝"}));expect(await screen.findByText("이 날짜의 스크리닝은 이미 완료되었습니다.")).toBeVisible();expect(screen.getByText(/상태: succeeded/)).toBeVisible();expect(screen.getByText(/후보: 1 \/ 저장: 1/)).toBeVisible();expect(latestCalls).toBe(2);});
});

describe("exact helpers",()=>{it.each([["0.03","3%"],["0.00125","0.125%"],["0","0%"]])("formats %s",(value,expected)=>expect(formatPercent(value)).toBe(expected));it("formats null",()=>expect(formatPercent(null)).toBe("—"));it("compares exact large decimals",()=>expect(compareDecimalStrings("900719925474099312345.01","900719925474099312345.001")).toBeGreaterThan(0));});
