"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { compareDecimal } from "@/features/backtests/format";
import { getLatestWatchlist, getScreenerDefinitions, getWatchlistHistory, WatchlistApiError } from "../api";
import { formatDecimal } from "../format";
import type { ScreenerDefinitions, WatchlistItem } from "../types";
const LABELS:Record<string,string>={box_breakout:"박스권 돌파",trend_pullback:"추세 눌림목",volatility_contraction_breakout:"변동성 축소 돌파"};
export function ScreenerDashboard(){const[items,setItems]=useState<WatchlistItem[]>([]),[definitions,setDefinitions]=useState<ScreenerDefinitions|null>(null),[state,setState]=useState<"loading"|"ready"|"error">("loading"),[retry,setRetry]=useState(0),[tradingDate,setTradingDate]=useState(""),[setup,setSetup]=useState(""),[search,setSearch]=useState(""),[minimum,setMinimum]=useState("0");useEffect(()=>{let active=true;setState("loading");Promise.all([getLatestWatchlist(),getScreenerDefinitions(),getWatchlistHistory()]).then(([rows,defs,dates])=>{if(active){setItems(rows);setDefinitions(defs);setTradingDate(dates.slice().sort().at(-1)??"");setState("ready")}}).catch((error)=>{if(active)setState("error");void(error instanceof WatchlistApiError)});return()=>{active=false}},[retry]);const filtered=useMemo(()=>items.filter(item=>(!setup||item.matched_setups?.includes(setup))&&item.symbol.includes(search.trim().toUpperCase())&&compareDecimal(item.total_score,minimum)>=0).sort((a,b)=>a.rank-b.rank),[items,setup,search,minimum]);return <main className="watchlist-shell"><nav aria-label="주요 메뉴"><Link href="/watchlist">관심 종목</Link><Link href="/backtests">백테스트</Link><Link href="/screener" aria-current="page">스크리너</Link></nav><header className="watchlist-header"><p className="eyebrow">KOSPI MULTI-SETUP</p><h1>스윙 스크리너</h1><p>기술적 조건에 따라 선별된 관찰 후보입니다. 자동 매수 신호가 아닙니다.</p>{definitions&&<p>{definitions.screener_name} v{definitions.screener_version}</p>}</header>{state==="loading"&&<p role="status">스크리닝 결과를 불러오는 중…</p>}{state==="error"&&<div role="alert">결과를 불러오지 못했습니다. <button onClick={()=>setRetry(x=>x+1)}>다시 시도</button></div>}{state==="ready"&&<><section className="panel" aria-label="스크리너 필터"><label>설정<select value={setup} onChange={e=>setSetup(e.target.value)}><option value="">전체</option>{definitions?.setups.map(x=><option key={x.key} value={x.key}>{x.label}</option>)}</select></label><label>최소 점수<input value={minimum} inputMode="decimal" onChange={e=>setMinimum(e.target.value||"0")}/></label><label>종목 검색<input value={search} onChange={e=>setSearch(e.target.value)}/></label></section>{filtered.length===0?<p>조건에 맞는 저장된 후보가 없습니다.</p>:<section className="watchlist-list" aria-label="스크리닝 후보">{filtered.map(item=><article className="watchlist-card" key={item.symbol}><Link className="card-link" href={`/watchlist/${encodeURIComponent(tradingDate)}/${encodeURIComponent(item.symbol)}`}><h2>{item.rank}. {item.symbol}</h2><p>종합 점수 {formatDecimal(item.total_score)}</p><p><strong>{item.primary_setup?LABELS[item.primary_setup]:"기존 후보"}</strong></p><p>{(item.matched_setups??[]).map(x=>LABELS[x]).join(" · ")}</p><dl><div><dt>종가</dt><dd>{item.latest_close??"—"}</dd></div><div><dt>20일 평균 거래대금</dt><dd>{item.average_trading_value_20??"—"}</dd></div><div><dt>ATR 비율</dt><dd>{item.atr_pct??"—"}</dd></div></dl><p>{item.warnings.length?`경고 ${item.warnings.length}건`:"경고 없음"}</p></Link></article>)}</section>}</>}</main>}
