"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ApiRequestError, apiRequest } from "@/lib/api";

type Definitions = { screener_name: string; version: string; setup_keys: string[]; setup_labels: Record<string,string> };
type Candidate = { rank:number; symbol:string; total_score:string; primary_setup?:string|null; matched_setups?:string[]; average_trading_value_20?:string|null; atr_pct?:string|null; volume_ratio?:string|null; prior_short_volume_ratio?:string|null; breakout_volume_ratio?:string|null; warnings:string[] };
type Execution = { trading_date:string; status:string; started_at:string; finished_at?:string|null; candidate_count?:number|null; persisted_count?:number|null; skipped_reason?:string|null; trigger_type?:string|null };
type Sort = "rank"|"score"|"value"|"symbol";

const fallbackLabels:Record<string,string>={box_breakout:"박스권 돌파",trend_pullback:"추세 눌림목",volatility_contraction_breakout:"변동성 축소 돌파"};
const digits = (value:string) => { const [whole,fraction=""] = value.split("."); return [whole.replace(/^0+(?=\d)/,""),fraction.replace(/0+$/,"")] as const; };
export function compareDecimalStrings(left:string,right:string):number { const [li,lf]=digits(left),[ri,rf]=digits(right); if(li.length!==ri.length)return li.length-ri.length; const whole=li.localeCompare(ri); if(whole)return whole; const size=Math.max(lf.length,rf.length); return lf.padEnd(size,"0").localeCompare(rf.padEnd(size,"0")); }
export function formatPercent(value:string|null|undefined):string { if(value==null)return "—"; const [whole,fraction=""]=value.split("."); const combined=(whole+fraction.padEnd(2,"0")).replace(/^0+(?=\d)/,""); const split=Math.max(0,combined.length-Math.max(0,fraction.length-2)); const result=(split===combined.length?combined:`${combined.slice(0,split)||"0"}.${combined.slice(split)}`).replace(/\.0+$|(?<=\.[0-9]*)0+$/g,""); return `${result}%`; }
function setQuery(key:string,value:string,defaultValue="") { const query=new URLSearchParams(window.location.search); if(value===""||value===defaultValue)query.delete(key);else query.set(key,value); const suffix=query.toString(); history.replaceState(null,"",`${location.pathname}${suffix?`?${suffix}`:""}`); }

export function ScreenerDashboard(){
 const initial=useMemo(()=>new URLSearchParams(typeof window==="undefined"?"":window.location.search),[]);
 const [definitions,setDefinitions]=useState<Definitions|null>(null),[historyDates,setHistoryDates]=useState<string[]>([]),[items,setItems]=useState<Candidate[]>([]),[execution,setExecution]=useState<Execution|null>(null);
 const [date,setDate]=useState(initial.get("date")??""),[setup,setSetup]=useState(initial.get("setup")??""),[q,setQ]=useState(initial.get("q")??"");
 const [minScore,setMinScore]=useState(initial.get("minScore")??""),[minValue,setMinValue]=useState(initial.get("minValue")??""),[warningFree,setWarningFree]=useState(initial.get("warningFree")==="1"),[sort,setSort]=useState<Sort>((initial.get("sort") as Sort)||"rank");
 const [loading,setLoading]=useState(true),[running,setRunning]=useState<"normal"|"reanalysis"|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[operationError,setOperationError]=useState(""),[failedRequest,setFailedRequest]=useState<"bootstrap"|"date"|null>(null); const request=useRef(0), operation=useRef(0), mounted=useRef(true);
 const loadDate=useCallback(async(selected:string)=>{const id=++request.current;setLoading(true);setError("");setFailedRequest(null);try{const result=await apiRequest<Candidate[]>(`/watchlist/${encodeURIComponent(selected)}`);if(request.current===id)setItems(result);}catch{if(request.current===id){setError("스크리너 결과를 불러오지 못했습니다.");setFailedRequest("date");}}finally{if(request.current===id)setLoading(false);}},[]);
 const bootstrap=useCallback(async()=>{setLoading(true);setError("");setFailedRequest(null);try{const latest=apiRequest<Execution>("/admin/watchlist/executions/latest").catch(error=>{if(error instanceof ApiRequestError&&error.status===404)return null;throw error});const [defs,dates,latestExecution]=await Promise.all([apiRequest<Definitions>("/screener/definitions"),apiRequest<string[]>("/watchlist/history"),latest]);setDefinitions(defs);setHistoryDates(dates);setExecution(latestExecution);setDate(current=>current||dates[0]||"");if(dates.length===0)setLoading(false);}catch{setError("스크리너 정보를 불러오지 못했습니다.");setFailedRequest("bootstrap");setLoading(false);}},[]);
 useEffect(()=>{mounted.current=true;void bootstrap();return()=>{mounted.current=false;request.current+=1;operation.current+=1};},[bootstrap]);
 useEffect(()=>{if(date)void loadDate(date);},[date,loadDate]);
 useEffect(()=>{const restore=()=>{const query=new URLSearchParams(window.location.search);setDate(query.get("date")??"");setSetup(query.get("setup")??"");setQ(query.get("q")??"");setMinScore(query.get("minScore")??"");setMinValue(query.get("minValue")??"");setWarningFree(query.get("warningFree")==="1");setSort((query.get("sort") as Sort)||"rank");};window.addEventListener("popstate",restore);return()=>window.removeEventListener("popstate",restore);},[]);
 useEffect(()=>{setQuery("date",date);},[date]); useEffect(()=>{setQuery("setup",setup);},[setup]); useEffect(()=>{setQuery("q",q);},[q]); useEffect(()=>{setQuery("minScore",minScore,"0");},[minScore]); useEffect(()=>{setQuery("minValue",minValue,"0");},[minValue]); useEffect(()=>{setQuery("warningFree",warningFree?"1":"");},[warningFree]); useEffect(()=>{setQuery("sort",sort,"rank");},[sort]);
 const selectDate=(value:string)=>setDate(value);
 const execute=async(kind:"normal"|"reanalysis")=>{if(running)return;if(kind==="reanalysis"&&(!date||!historyDates.includes(date)))return;if(kind==="reanalysis"&&!window.confirm(`저장된 시장 데이터로 ${date} 결과를 다시 계산합니다.`))return;const id=++operation.current;setRunning(kind);setNotice("");setOperationError("");try{const result=await apiRequest<Execution>("/admin/watchlist/run",{method:"POST",body:JSON.stringify(kind==="reanalysis"?{trading_date:date,force_reanalysis:true}:{})});if(!mounted.current||operation.current!==id)return;if(kind==="normal"&&result.status==="skipped"&&result.skipped_reason==="already_completed"){setNotice("이 날짜의 스크리닝은 이미 완료되었습니다.");const latest=await apiRequest<Execution>("/admin/watchlist/executions/latest");if(!mounted.current||operation.current!==id)return;setExecution(latest);if(date)await loadDate(date);return;}setExecution(result);const dates=await apiRequest<string[]>("/watchlist/history");if(!mounted.current||operation.current!==id)return;setHistoryDates(dates);if(result.trading_date===date)await loadDate(result.trading_date);else selectDate(result.trading_date);}catch(value){if(!mounted.current||operation.current!==id)return;const conflict=value instanceof ApiRequestError&&value.status===409;setOperationError(conflict?(kind==="reanalysis"?"다른 분석이 실행 중이거나 이전 성공 이력이 없습니다.":"이미 스크리닝이 실행 중입니다."):(kind==="reanalysis"?"다시 분석에 실패했습니다. 이전 결과는 유지됩니다.":"스크리닝 실행에 실패했습니다."));}finally{if(mounted.current&&operation.current===id)setRunning(null)}};
 const shown=useMemo(()=>items.filter(item=>(!setup||item.matched_setups?.includes(setup))&&(!q||item.symbol.includes(q))&&(!minScore||minScore==="0"||compareDecimalStrings(item.total_score,minScore)>=0)&&(!minValue||minValue==="0"||compareDecimalStrings(item.average_trading_value_20??"0",minValue)>=0)&&(!warningFree||item.warnings.length===0)).sort((a,b)=>sort==="rank"?a.rank-b.rank:sort==="score"?compareDecimalStrings(b.total_score,a.total_score):sort==="value"?compareDecimalStrings(b.average_trading_value_20??"0",a.average_trading_value_20??"0"):a.symbol.localeCompare(b.symbol)),[items,setup,q,minScore,minValue,warningFree,sort]);
 const labels=definitions?.setup_labels??fallbackLabels;
 return <main><nav><Link href="/dashboard">대시보드</Link> · <Link href="/watchlist">관심 종목</Link> · <strong>스크리너</strong></nav><h1>멀티 셋업 스윙 스크리너</h1><p>{definitions?`${definitions.screener_name} v${definitions.version}`:"정의 로딩 중"}</p><section aria-label="실행 정보"><p>선택 결과일: {date||"—"}</p><p>{execution?<>최근 실행일: {execution.trading_date} / 상태: {execution.status}</>:"실행 이력 없음"}</p><p>시작: {execution?.started_at??"—"} / 종료: {execution?.finished_at??"—"}</p><p>후보: {execution?.candidate_count??"—"} / 저장: {execution?.persisted_count??"—"}</p><button onClick={()=>void execute("normal")} disabled={running!==null}>{running==="normal"?"실행 중…":"오늘 스크리닝"}</button> <button onClick={()=>void execute("reanalysis")} disabled={running!==null||!date||!historyDates.includes(date)}>{running==="reanalysis"?"다시 분석 중…":"선택 날짜 다시 분석"}</button></section>{notice&&<p role="status">{notice}</p>}{operationError&&<div role="alert">{operationError}</div>}<p>기술적 조건은 미래 수익을 보장하지 않으며 투자 자문이 아닙니다.</p>
 <section aria-label="필터"><label>날짜 <select value={date} onChange={e=>selectDate(e.target.value)}>{historyDates.map(value=><option key={value}>{value}</option>)}</select></label><label> 셋업 <select value={setup} onChange={e=>setSetup(e.target.value)}><option value="">전체</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label> 최소 점수 <input value={minScore} onChange={e=>setMinScore(e.target.value)}/></label><label> 최소 거래대금 <input value={minValue} onChange={e=>setMinValue(e.target.value)}/></label><label> 종목 <input value={q} onChange={e=>setQ(e.target.value)}/></label><label><input type="checkbox" checked={warningFree} onChange={e=>setWarningFree(e.target.checked)}/> 경고 없음</label><label> 정렬 <select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="rank">순위</option><option value="score">점수</option><option value="value">거래대금</option><option value="symbol">종목</option></select></label></section>
 {loading?<p>불러오는 중…</p>:error?<div role="alert"><p>{error}</p><button onClick={()=>void (failedRequest==="date"&&date?loadDate(date):bootstrap())}>다시 시도</button></div>:shown.length===0?<p>선택한 날짜의 후보가 없습니다.</p>:<div>{shown.map(item=><article key={item.symbol}><h2><a href={`/watchlist/${date}/${item.symbol}`}>{item.symbol}</a></h2><p>{item.rank}위 · {item.total_score}점 · {item.primary_setup?labels[item.primary_setup]:"기존 결과"}</p><p>평균 거래대금: {item.average_trading_value_20??"—"} / ATR: {formatPercent(item.atr_pct)}</p>{item.primary_setup==="box_breakout"&&<p>돌파 거래량 배수: {item.volume_ratio??"—"}</p>}{item.primary_setup==="trend_pullback"&&<p>직전 단기 거래량 비율: {item.prior_short_volume_ratio??"—"}</p>}{item.primary_setup==="volatility_contraction_breakout"&&<><p>돌파 거래량 배수: {item.breakout_volume_ratio??"—"}</p><p>직전 단기 거래량 비율: {item.prior_short_volume_ratio??"—"}</p></>}</article>)}</div>}</main>;
}
