"use client";
import { useEffect, useState } from "react";
import { getBacktestAnalysis } from "../api";
import { displayDecimal, money, percent } from "../format";
import type { BacktestAnalysis as Analysis } from "../types";
const cache=new Map<string,Analysis>(); const pending=new Map<string,Promise<Analysis>>();
function load(id:string){if(cache.has(id))return Promise.resolve(cache.get(id)!);if(!pending.has(id))pending.set(id,getBacktestAnalysis(id).then(x=>{if(!Array.isArray(x.cumulative_realized_pnl)||!Array.isArray(x.by_symbol)||!Array.isArray(x.by_exit_reason)||!Array.isArray(x.by_month))throw new Error("Invalid analysis response");cache.set(id,x);return x}).finally(()=>pending.delete(id)));return pending.get(id)!}
const fields=[
 ["trade_count","거래 수","plain"],["winning_trades","수익 거래","plain"],["losing_trades","손실 거래","plain"],["breakeven_trades","손익분기 거래","plain"],["win_rate","승률","percent"],["gross_profit","총이익","money"],["gross_loss","총손실","money"],["net_profit","순이익","money"],["average_trade_pnl","평균 거래 손익","money"],["average_win","평균 수익","money"],["average_loss","평균 손실","money"],["largest_win","최대 수익","money"],["largest_loss","최대 손실","money"],["profit_factor","손익비","plain"],["average_holding_days","평균 보유일","plain"],["max_consecutive_wins","최대 연속 수익","plain"],["max_consecutive_losses","최대 연속 손실","plain"],["max_realized_pnl_drawdown","최대 실현 손익 낙폭","money"]] as const;
function Chart({title,description,values}:{title:string;description:string;values:string[]}){const nums=values.map(Number).filter(Number.isFinite),max=Math.max(1,...nums.map(Math.abs));return <figure aria-label={title}><figcaption><strong>{title}</strong></figcaption>{values.length?<svg role="img" aria-label={title} viewBox="0 0 600 140"><title>{title}</title><desc>{description}</desc><polyline fill="none" stroke="currentColor" strokeWidth="3" points={nums.map((v,i)=>`${i/Math.max(1,nums.length-1)*590+5},${70-v/max*60}`).join(" ")}/></svg>:<p>표시할 데이터가 없습니다.</p>}</figure>}
function Table({title,heads,rows}:{title:string;heads:string[];rows:string[][]}){return <section><h3>{title}</h3><div className="table-scroll"><table><thead><tr>{heads.map(x=><th scope="col" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>표시할 데이터가 없습니다.</p>}</div></section>}
export function BacktestAnalysis({runId}:{runId:string}){const[data,setData]=useState<Analysis|null>(cache.get(runId)??null),[error,setError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;setData(cache.get(runId)??null);setError(false);load(runId).then(x=>{if(active)setData(x)}).catch(()=>{if(active)setError(true)});return()=>{active=false}},[runId,retry]);if(error)return <section className="panel error-state"><h2>실현 거래 분석</h2><p>분석을 불러오지 못했습니다.</p><button onClick={()=>setRetry(x=>x+1)}>다시 시도</button></section>;if(!data)return <section className="panel" aria-busy="true"><h2>실현 거래 분석</h2><p>분석을 불러오는 중입니다.</p></section>;const summary={...data.summary,trade_count:data.trade_count} as unknown as Record<string,string|number|null>;const fmt=(v:string|number|null,t:string)=>t==="money"?money(v):t==="percent"?percent(v):displayDecimal(v);return <section className="panel analysis"><h2>실현 거래 분석</h2><p className="muted">저장된 실현 거래만을 설명적으로 분석합니다. 미실현 손익과 포트폴리오 현금 제약은 포함하지 않습니다.</p><dl className="metric-grid">{fields.map(([k,l,t])=><div key={k}><dt>{l}</dt><dd>{fmt(summary[k]??null,t)}</dd></div>)}</dl><Chart title="실현 거래 기준 누적 순손익" description={data.cumulative_realized_pnl.map(x=>`${x.exit_date} ${x.symbol}, 거래 ${x.net_pnl}, 누적 ${x.cumulative_net_pnl}`).join("; ")} values={data.cumulative_realized_pnl.map(x=>x.cumulative_net_pnl)}/><Chart title="실현 손익 기준 낙폭" description={data.cumulative_realized_pnl.map(x=>`${x.exit_date} ${x.symbol}: ${x.realized_drawdown}`).join("; ")} values={data.cumulative_realized_pnl.map(x=>`-${x.realized_drawdown}`)}/><Chart title="월별 실현 순손익" description={data.by_month.map(x=>`${x.month}: ${x.net_profit} (${Number(x.net_profit)>0?"양수":Number(x.net_profit)<0?"음수":"0"})`).join("; ")} values={data.by_month.map(x=>x.net_profit)}/><Table title="종목별 성과" heads={["종목","거래","수익","손실","손익분기","승률","순이익","평균 손익","평균 보유일","최대 수익","최대 손실"]} rows={data.by_symbol.map(x=>[x.symbol,String(x.trade_count),String(x.winning_trades),String(x.losing_trades),String(x.breakeven_trades),percent(x.win_rate),money(x.net_profit),money(x.average_trade_pnl),displayDecimal(x.average_holding_days),money(x.largest_win),money(x.largest_loss)])}/><Table title="청산 사유별 성과" heads={["사유","거래","비중","수익","손실","손익분기","승률","순이익","평균 손익","평균 보유일"]} rows={data.by_exit_reason.map(x=>[x.exit_reason,String(x.trade_count),percent(x.trade_share),String(x.winning_trades),String(x.losing_trades),String(x.breakeven_trades),percent(x.win_rate),money(x.net_profit),money(x.average_trade_pnl),displayDecimal(x.average_holding_days)])}/><Table title="월별 성과" heads={["월","거래","수익","손실","손익분기","승률","총이익","총손실","순이익","평균 손익","평균 보유일"]} rows={data.by_month.map(x=>[x.month,String(x.trade_count),String(x.winning_trades),String(x.losing_trades),String(x.breakeven_trades),percent(x.win_rate),money(x.gross_profit),money(x.gross_loss),money(x.net_profit),money(x.average_trade_pnl),displayDecimal(x.average_holding_days)])}/></section>}
