import { useEffect, useState } from "react";
import { cachedBacktestAnalysis, loadBacktestAnalysis } from "../analysis-cache";
import { compareDecimal, displayDecimal, money, percent } from "../format";
import type { BacktestAnalysis, BacktestRun } from "../types";
import type { PortfolioResult } from "../types";
import { cachedBacktestPortfolio, loadBacktestPortfolio } from "../portfolio-cache";
import { METRIC_LABELS, metricValue } from "./metrics";
const LEGACY_KEYS=["total_signals","entered_trades","skipped_signals","win_rate","net_profit","total_return","average_holding_days","maximum_gain","maximum_loss"];
const METRICS = [["trade_count","거래 수","plain"],["winning_trades","수익 거래","plain"],["losing_trades","손실 거래","plain"],["breakeven_trades","손익분기 거래","plain"],["win_rate","승률","percent"],["net_profit","순이익","money"],["average_trade_pnl","평균 거래 손익","money"],["average_win","평균 수익","money"],["average_loss","평균 손실","money"],["largest_win","최대 수익","money"],["largest_loss","최대 손실","money"],["profit_factor","손익비","plain"],["average_holding_days","평균 보유일","plain"],["max_consecutive_wins","최대 연속 수익","plain"],["max_consecutive_losses","최대 연속 손실","plain"],["max_realized_pnl_drawdown","최대 실현 손익 낙폭","money"]] as const;
type Value=string|number|null;
const values=(a:BacktestAnalysis)=>({...a.summary,trade_count:a.trade_count}) as unknown as Record<string,Value>;
function relation(a:Value,b:Value){if(a==null||b==null)return "비교 불가";const order=compareDecimal(a,b);return order===0?"같음":order>0?"더 높음":"더 낮음"}
function format(value:Value,kind:string){return kind==="money"?money(value):kind==="percent"?percent(value):displayDecimal(value)}
const PORTFOLIO_METRICS = [["initial_capital","초기 자본","money"],["final_equity","최종 자산","money"],["final_cash","최종 현금","money"],["net_profit","순이익","money"],["total_return","총수익률","percent"],["max_drawdown","최대 포트폴리오 낙폭","money"],["max_drawdown_pct","최대 포트폴리오 낙폭 비율","percent"],["average_capital_utilization","평균 자본 사용률","percent"],["maximum_open_positions_used","최대 동시 보유 수","plain"]] as const;
function AnalysisColumn({run,other,otherRun}:{run:BacktestRun;other:BacktestAnalysis|null;otherRun:BacktestRun}){const[analysis,setAnalysis]=useState<BacktestAnalysis|null>(cachedBacktestAnalysis(run.id)??null),[portfolio,setPortfolio]=useState<PortfolioResult|null>(cachedBacktestPortfolio(run.id)??null),[error,setError]=useState(false),[portfolioError,setPortfolioError]=useState(false),[retry,setRetry]=useState(0);useEffect(()=>{let active=true;setError(false);loadBacktestAnalysis(run.id).then(result=>{if(active)setAnalysis(result)}).catch(()=>{if(active)setError(true)});if(run.execution_mode==="portfolio"){setPortfolioError(false);loadBacktestPortfolio(run.id).then(result=>{if(active)setPortfolio(result)}).catch(()=>{if(active)setPortfolioError(true)})}return()=>{active=false}},[run.id,run.execution_mode,retry]);const peerPortfolio=otherRun.execution_mode==="portfolio"?cachedBacktestPortfolio(otherRun.id)??null:null;return <article aria-label={`실행 ${run.id} 분석 비교`}><h3>실행 {run.id}</h3><p>{run.start_date} – {run.end_date}</p><p><strong>실행 모드:</strong> {run.execution_mode === "portfolio" ? "포트폴리오" : "독립 거래"}</p><h4>파라미터</h4><dl>{Object.entries(run.parameters).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><h4>공통 실행 지표</h4><dl>{LEGACY_KEYS.filter(key=>key!=="max_drawdown").map(key=>{const own=run.result?.[key as keyof typeof run.result]??null,peer=otherRun.result?.[key as keyof typeof otherRun.result]??null;return <div key={key}><dt>{METRIC_LABELS[key]}</dt><dd>{metricValue(key,own)} <small>({relation(own,peer)}; 설명적 비교)</small></dd></div>})}</dl><h4>포트폴리오 전용 지표</h4>{run.execution_mode!=="portfolio"?<p>해당 없음 — 독립 거래에는 포트폴리오 지표가 없습니다.</p>:portfolioError?<p role="alert">포트폴리오 비교 데이터를 불러오지 못했습니다.</p>:!portfolio?<p aria-busy="true">포트폴리오 비교 데이터를 불러오는 중입니다.</p>:<dl>{PORTFOLIO_METRICS.map(([key,label,kind])=>{const own=portfolio[key] as Value,peer=peerPortfolio?.[key] as Value??null;return <div key={key}><dt>{label}</dt><dd>{format(own,kind)} <small>({peerPortfolio?relation(own,peer):"비교 불가"}; 설명적 비교)</small></dd></div>})}</dl>}{error?<><p role="alert">이 실행의 분석을 불러오지 못했습니다.</p><button onClick={()=>setRetry(x=>x+1)}>분석 다시 시도</button></>:!analysis?<p aria-busy="true">이 실행의 분석을 불러오는 중입니다.</p>:<dl>{METRICS.map(([key,label,kind])=>{const own=values(analysis)[key],peer=other?values(other)[key]:null;return <div key={key}><dt>{label}</dt><dd>{format(own,kind)} <small>({relation(own,peer)}; 설명적 비교)</small></dd></div>})}</dl>}</article>}
export function BacktestComparison({runs}:{runs:BacktestRun[]}){const[loaded,setLoaded]=useState<Record<string,BacktestAnalysis>>({});useEffect(()=>{let active=true;for(const run of runs)loadBacktestAnalysis(run.id).then(a=>{if(active)setLoaded(current=>({...current,[run.id]:a}))}).catch(()=>undefined);return()=>{active=false}},[runs]);return <section className="panel"><h2>실현 거래 분석 비교</h2><p className="muted">두 완료 실행의 저장된 실현 거래를 설명적으로 비교합니다. 통계적 유의성을 주장하지 않으며 높고 낮음은 우열을 뜻하지 않습니다.</p>{runs.length<2?<p>완료된 서로 다른 실행 두 개를 선택하세요.</p>:<div className="comparison">{runs.map((run,index)=><AnalysisColumn key={run.id} run={run} otherRun={runs[1-index]} other={loaded[runs[1-index].id]??cachedBacktestAnalysis(runs[1-index].id)??null}/>)}</div>}</section>}
